services:
  node:
    build: .
    ports:
      - "8080:3000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    environment:
     - POSTGRES_DB=${DATABASE_NAME}
     - POSTGRES_USER=${DATABASE_USER}
     - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
     - PGPORT=${DATABASE_PORT}
    env_file:
      - .env
    ports:
    - '${DATABASE_PORT}:${DATABASE_PORT}'
    volumes:
    - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: